import './globals.css'
import Link from "next/link";

export const metadata = {
  title: `JD's Portfolio`,
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body suppressHydrationWarning={true}>
      <header>
        <Link href="/">Portfolio</Link>
        <nav>
          <ul>
            <li><Link href="/profile">Profile</Link></li>
            <li><Link href="/publish">Publish</Link></li>
            <li><Link href="/develop">Develop</Link></li>
            <li><Link href="/contact">Contact</Link></li>
          </ul>
        </nav>
      </header>
      {children}
      <footer>Made by JD</footer>
      </body>
    </html>
  )
}
