import './globals.css'
import Link from "next/link";
import Navigation from "@/app/component/navigation";

export const metadata = {
    title: `JD's Portfolio`,
    description: 'Generated by create next app',
}

const navigationMenu = ['Profile', 'Publish', 'Develop', 'Contact'];

export default function RootLayout({children}) {
    return (
        <html lang="ko">
        <body suppressHydrationWarning={true}>
        <div className="wrap">
            <header>
                <h1><Link href="/">Portfolio</Link></h1>
                <nav>
                    <ul>
                        <Navigation nav={navigationMenu}/>
                    </ul>
                </nav>
            </header>
            {children}
            <footer>
                <p className="skills">해당 사이트는 next.js로 구성되어 있습니다.</p>
                <p className="made">Made by JD</p>
            </footer>
        </div>
        </body>
        </html>
    )
}
